# Q1

In [4]:
dict_1 = {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

result = [{'Boys': boys_height, 'Girls': girls_height} for boys_height, girls_height in zip(dict_1['Boys'], dict_1['Girls'])]

print(result)

li = []

for i in range(len(dict_1["Boys"])):
  li.append({"Boys": dict_1["Boys"][i], "Girls": dict_1["Girls"][i]})

print(li)

[{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {'Boys': 74, 'Girls': 61}]
[{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {'Boys': 74, 'Girls': 61}]


# Q2

## a)

In [5]:
import numpy as np
arr = np.random.randint(50, size = (3, 3))
print(arr)
print("Mean: ", np.mean(arr, axis = 1))
print("Standard Deviation: ", np.std(arr, axis = 1))
print("Variance: ", np.var(arr, axis = 1))


[[10 39 27]
 [44 12 34]
 [23 30 40]]
Mean:  [25.33333333 30.         31.        ]
Standard Deviation:  [11.8977122  13.3666251   6.97614985]
Variance:  [141.55555556 178.66666667  48.66666667]


## b)

In [ ]:
arr = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])
sorted = np.sort(arr)


## c)

In [4]:
import numpy as np
m = input("Enter the number of rows (m): ")
n = input("Enter the number of columns (n): ")

arr = np.random.randint(0, 10, size=(m, n))

print("Original Array:")
print(arr)
print("\nShape:", arr.shape)
print("Type:", type(arr))
print("Data Type:", arr.dtype)

reshaped_array = arr.reshape(n, m)

print("\nReshaped Array:")
print(reshaped_array)
print("\nShape:", reshaped_array.shape)
print("Type:", type(reshaped_array))
print("Data Type:", reshaped_array.dtype)


<class 'TypeError'>: unsupported operand type(s) for *: 'PyodideFuture' and 'PyodideFuture'

Enter the number of rows (m):  3
Enter the number of columns (n):  4


# Q3

## a)

In [12]:
import pandas as pd
import numpy as np
r = 50
c = 3
data = np.random.rand(r, c)
df = pd.DataFrame(data, columns = ['c1', 'c2', 'c3'])
nullVals = int(0.1 * df.size)
nullRow = np.random.choice(df.index, nullVals)
nullCol = np.random.choice(df.columns, nullVals)
df.iloc[nullRow, nullCol] = np.nan

df

<class 'IndexError'>: arrays used as indices must be of integer (or boolean) type